[pytest]

addopts =
    -v
    --strict-markers
    --cov=app



testpaths = tests


markers =
    smoke: дым тесты
    regression: регрессивные тесты
    slow: медленны тесты
    asyncio: асинхронное тестирование
